Use agnostic program names

diff --git a/tests/run-tests b/tests/run-tests
--- a/tests/run-tests
+++ b/tests/run-tests
@@ -2,15 +2,26 @@
 
 export SECRETS=".secrets.json"
 
-cd $(dirname $(git rev-parse --git-dir))/tests
-FILES=$(find -executable | grep -v $(basename $0))
+PROJECT=$(realpath $(dirname $(git rev-parse --git-dir)))
 
+# Automate finding tests to execute
+cd $PROJECT/tests
+FILES=$(find -executable -not -path "\." | grep -v $(basename $0))
+
+# The base status of tests is a pass
+cd $PROJECT
 STATUS=0
 
 for TEST in $FILES
 do
-	$TEST
-	STATUS=$(( $STATUS | $? ))
+	if [ $1 = "--silence-pass" ]
+	then
+		$PROJECT/tests/$TEST 1>/dev/null
+	else
+		$PROJECT/tests/$TEST
+	fi
+
+	STATUS=$(( $STATUS | $? )) # OR current status with return code
 done
 
 exit $STATUS
